/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "rcc.h"
#include "I2C.h"
#include "reset_function.h"
#include "iperipheral.h"
#include <string.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void enable_clock()
{
    *RCC_CR |= HSI_ON;
    while (HSI_RDY != 2);

    *RCC_CFGR |= HSI_SYSCLK;
    while ((*RCC_CFGR & SYSCLK_RDY_FLAG) != 0);

    *RCC_CFGR |= AHB_CLK_NOT_DIVIDE;
    *RCC_CFGR |= APB1_CLK_NOT_DIVIDE;
    *RCC_CFGR |= APB2_CLK_NOT_DIVIDE;

    *RCC_APB2ENR |= PORTB_EN | AFIO_EN;
    *RCC_APB1ENR |= I2C_EN;
}

void initialize()
{
	// PB6 CLK
	*GPIOB_CRL |= (GPIO_CNF_OUTPUT_AF_OD << CNF6) | (GPIO_MODE_OUTPUT_10MHZ << MODE6);
	// P MOSI
	*GPIOB_CRL |= (GPIO_CNF_OUTPUT_AF_OD << CNF7) | (GPIO_MODE_OUTPUT_10MHZ << MODE7);
}

int main(void)
{
    /* Loop forever */
	reset_sys();
	enable_clock();
	initialize();
	*I2C_CR1 |= Stop_Bit;
	I2C_Init(FERQ_8MHZ, 'M', Standa_Mode);
	while (1)
	{
		uint8_t msg[] = "Hello world!";
		int size = sizeof(msg)/sizeof(msg[0]);
		I2C_Transmit_LCD(0x27<<1, msg, size);
		delay_ms(500);
	}
}
